### ISSUE TITLE
Add support for Python 3.11

### ISSUE THREAD

**Issue by lyfofvipin** [vipin3699/File-Server#63]
Getting the error while running the app on python3.11

```
(vert_3) [vipikuma@kvy File-Server]$ python3 run.py 
Traceback (most recent call last):
  File "/home/vipikuma/my_data/File-Server/run.py", line 1, in <module>
    from src import app, Product_Versions, config_dir, result_base_dir_path, create_file_structure, port, skip_product_version_creation_for_products
  File "/home/vipikuma/my_data/File-Server/src/__init__.py", line 15, in <module>
    from src import routs
  File "/home/vipikuma/my_data/File-Server/src/routs.py", line 3, in <module>
    from src.forms import RegistrationForm, LoginForm, UpdateAccount, ChangePasswordForm
  File "/home/vipikuma/my_data/File-Server/src/forms.py", line 6, in <module>
    from src.models import User
  File "/home/vipikuma/my_data/File-Server/src/models.py", line 20, in <module>
    db.create_all()
  File "/home/vipikuma/work_stuff/vert_3/lib64/python3.11/site-packages/flask_sqlalchemy/extension.py", line 884, in create_all
    self._call_for_binds(bind_key, "create_all")
  File "/home/vipikuma/work_stuff/vert_3/lib64/python3.11/site-packages/flask_sqlalchemy/extension.py", line 855, in _call_for_binds
    engine = self.engines[key]
             ^^^^^^^^^^^^
  File "/home/vipikuma/work_stuff/vert_3/lib64/python3.11/site-packages/flask_sqlalchemy/extension.py", line 636, in engines
    app = current_app._get_current_object()  # type: ignore[attr-defined]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vipikuma/work_stuff/vert_3/lib64/python3.11/site-packages/werkzeug/local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
(vert_3) [vipikuma@kvy File-Server]$ 
(vert_3) [vipikuma@kvy File-Server]$ python
Python 3.11.6 (main, Oct  3 2023, 00:00:00) [GCC 12.3.1 20230508 (Red Hat 12.3.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 

```

**Comment by lyfofvipin** [comment]
fixed by above changes.
